
import React, { useState } from 'react';
import { HeartPulse, CheckCircle2, ArrowRightLeft, ShieldCheck, AlertCircle, Download, Loader2, TrendingUp, ShieldAlert, Zap } from 'lucide-react';
import { PredictionResult } from '../../types.ts';
import { jsPDF } from 'jspdf';

export const RecsView: React.FC<{prediction: PredictionResult | null}> = ({ prediction }) => {
  const [isDownloading, setIsDownloading] = useState(false);

  if (!prediction) {
    return (
      <div className="h-[60vh] flex flex-col items-center justify-center bg-white dark:bg-slate-900 rounded-[40px] border border-slate-200 dark:border-slate-800 border-dashed">
         <HeartPulse size={48} className="text-slate-200 dark:text-slate-700 mb-4" />
         <h2 className="text-xl font-bold text-slate-900 dark:text-white">Recommendations Idle</h2>
         <p className="text-slate-500 dark:text-slate-400 text-sm">Complete a clinical analysis to see suggested therapeutic optimizations.</p>
      </div>
    );
  }

  const handleDownloadPDF = async () => {
    setIsDownloading(true);
    
    try {
      await new Promise(resolve => setTimeout(resolve, 800));
      const doc = new jsPDF();
      const margin = 20;
      let y = 20;

      doc.setFontSize(22);
      doc.setTextColor(30, 136, 229);
      doc.text("DDIPS CLINICAL PROTOCOL", margin, y);
      
      y += 10;
      doc.setFontSize(10);
      doc.setTextColor(100, 116, 139);
      doc.text(`REPORT ID: ${prediction.id} | ${new Date(prediction.timestamp).toLocaleString()}`, margin, y);
      
      y += 15;
      doc.setDrawColor(226, 232, 240);
      doc.line(margin, y, 190, y);

      y += 15;
      doc.setFontSize(16);
      doc.setTextColor(30, 41, 59);
      doc.text("Medication Profile Analysis", margin, y);
      
      y += 10;
      doc.setFontSize(12);
      doc.text(`Drugs: ${prediction.drugs.join(', ')}`, margin, y);
      
      y += 8;
      const riskColor = prediction.riskLevel === 'HIGH' ? [211, 47, 47] : prediction.riskLevel === 'MODERATE' ? [237, 108, 2] : [46, 125, 50];
      doc.setTextColor(riskColor[0], riskColor[1], riskColor[2]);
      doc.text(`Risk Assessment: ${prediction.riskLevel} (${prediction.severity} SEVERITY)`, margin, y);

      y += 15;
      doc.setFontSize(14);
      doc.setTextColor(30, 41, 59);
      doc.text("Management Strategy", margin, y);
      
      y += 8;
      doc.setFontSize(11);
      doc.setTextColor(71, 85, 105);
      const splitStrategy = doc.splitTextToSize(prediction.recommendation, 170);
      doc.text(splitStrategy, margin, y);
      y += (splitStrategy.length * 6) + 10;

      if (prediction.recommendations && prediction.recommendations.length > 0) {
        doc.setFontSize(14);
        doc.setTextColor(30, 41, 59);
        doc.text("Suggested Alternatives", margin, y);
        y += 8;
        prediction.recommendations.forEach(rec => {
           doc.setFontSize(11);
           doc.setTextColor(46, 125, 50);
           doc.text(`Alternative: ${rec.saferAlternative}`, margin, y);
           y += 6;
           doc.setFontSize(10);
           doc.setTextColor(71, 85, 105);
           const benefitText = doc.splitTextToSize(`Benefit: ${rec.clinicalBenefit}`, 160);
           doc.text(benefitText, margin + 5, y);
           y += (benefitText.length * 5) + 5;
        });
      }

      doc.setFontSize(8);
      doc.setTextColor(148, 163, 184);
      doc.text("Generated by DDIPS Enterprise AI. This document is for clinical decision support only.", margin, 280);

      doc.save(`Clinical_Protocol_${prediction.id}.pdf`);
    } catch (error) {
      console.error("PDF Generation Error:", error);
      alert("Failed to generate PDF. Please try again.");
    } finally {
      setIsDownloading(false);
    }
  };

  return (
    <div className="space-y-8 animate-in fade-in duration-500">
      <div>
         <h2 className="text-3xl font-bold text-slate-900 dark:text-white mb-1">Clinical Recommendations</h2>
         <p className="text-slate-500 dark:text-slate-400">AI-suggested therapeutic adjustments and safer alternatives.</p>
      </div>

      <div className="glass-panel p-8 rounded-[40px] border-none bg-blue-600 text-white shadow-2xl relative overflow-hidden group">
         <div className="absolute top-0 right-0 p-12 text-white/5 opacity-50"><HeartPulse size={140} /></div>
         <div className="relative z-10 flex flex-col md:flex-row items-center gap-8">
            <div className="w-20 h-20 bg-white/10 rounded-3xl flex items-center justify-center text-white backdrop-blur-md border border-white/20">
               <ShieldCheck size={40} />
            </div>
            <div className="flex-1 text-center md:text-left">
               <h3 className="text-2xl font-bold mb-2">Therapeutic Management Strategy</h3>
               <p className="text-blue-100 leading-relaxed text-lg font-medium opacity-90 max-w-2xl">
                 {prediction.recommendation}
               </p>
            </div>
            <button 
              onClick={handleDownloadPDF}
              disabled={isDownloading}
              className={`bg-white text-blue-600 px-8 py-4 rounded-2xl font-bold shadow-xl active:scale-95 transition-all whitespace-nowrap flex items-center gap-3
                ${isDownloading ? 'opacity-70 cursor-not-allowed' : 'hover:bg-blue-50'}`}
            >
               {isDownloading ? (
                 <>
                   <Loader2 className="animate-spin" size={20} />
                   Compiling...
                 </>
               ) : (
                 <>
                   <Download size={20} />
                   Download PDF
                 </>
               )}
            </button>
         </div>
      </div>

      <div className="grid grid-cols-1 gap-8">
         <h4 className="text-xs font-black text-slate-400 dark:text-slate-500 uppercase tracking-widest ml-2">Comparative Clinical Analysis</h4>
         {prediction.recommendations && prediction.recommendations.length > 0 ? prediction.recommendations.map((rec, i) => (
            <div key={i} className="glass-panel p-8 rounded-[40px] border border-white dark:border-slate-800 shadow-xl hover:-translate-y-1 transition-all group overflow-hidden relative">
               <div className="absolute top-0 right-0 w-24 h-24 bg-emerald-500/5 -mr-8 -mt-8 rounded-full blur-2xl"></div>
               
               <div className="flex flex-col md:flex-row gap-8 relative z-10">
                  <div className="md:w-1/3 border-b md:border-b-0 md:border-r border-slate-100 dark:border-slate-800 pb-6 md:pb-0 md:pr-8">
                    <div className="flex items-center justify-between mb-4">
                       <span className="text-2xl font-bold text-slate-900 dark:text-white group-hover:text-blue-600 dark:group-hover:text-blue-400 transition-colors">
                        {rec.saferAlternative}
                       </span>
                    </div>
                    <div className="p-4 bg-emerald-50 dark:bg-emerald-900/20 rounded-2xl border border-emerald-100 dark:border-emerald-800/50 mb-4">
                       <p className="text-[10px] font-black text-emerald-600 dark:text-emerald-400 uppercase tracking-widest mb-1">Primary Benefit</p>
                       <p className="text-sm font-bold text-slate-800 dark:text-slate-200">{rec.clinicalBenefit}</p>
                    </div>
                    <div className="space-y-2">
                      <div className="flex justify-between items-center mb-1">
                        <span className="text-[10px] font-bold text-slate-400 uppercase tracking-widest">Advantage Score</span>
                        <span className="text-xs font-black text-blue-600 dark:text-blue-400">{rec.benefitScore}%</span>
                      </div>
                      <div className="h-1.5 w-full bg-slate-100 dark:bg-slate-800 rounded-full overflow-hidden">
                        <div 
                          className="h-full bg-gradient-to-r from-blue-500 to-emerald-400 transition-all duration-1000"
                          style={{ width: `${rec.benefitScore}%` }}
                        ></div>
                      </div>
                    </div>
                  </div>

                  <div className="md:w-2/3 grid grid-cols-1 md:grid-cols-2 gap-6">
                    <div className="space-y-4">
                      <div className="flex items-start gap-3">
                        <div className="w-8 h-8 rounded-lg bg-blue-50 dark:bg-blue-900/30 flex items-center justify-center text-blue-600 dark:text-blue-400 flex-shrink-0">
                          <TrendingUp size={16} />
                        </div>
                        <div>
                          <p className="text-[10px] font-black text-slate-400 dark:text-slate-500 uppercase tracking-widest mb-1">Efficacy Comparison</p>
                          <p className="text-sm text-slate-700 dark:text-slate-300 leading-relaxed">{rec.efficacyComparison}</p>
                        </div>
                      </div>

                      <div className="flex items-start gap-3">
                        <div className="w-8 h-8 rounded-lg bg-amber-50 dark:bg-amber-900/30 flex items-center justify-center text-amber-600 dark:text-amber-400 flex-shrink-0">
                          <Zap size={16} />
                        </div>
                        <div>
                          <p className="text-[10px] font-black text-slate-400 dark:text-slate-500 uppercase tracking-widest mb-1">Side Effect Profile</p>
                          <p className="text-sm text-slate-700 dark:text-slate-300 leading-relaxed">{rec.sideEffectProfile}</p>
                        </div>
                      </div>
                    </div>

                    <div className="space-y-4">
                      <div className="flex items-start gap-3">
                        <div className="w-8 h-8 rounded-lg bg-red-50 dark:bg-red-900/30 flex items-center justify-center text-red-600 dark:text-red-400 flex-shrink-0">
                          <ShieldAlert size={16} />
                        </div>
                        <div>
                          <p className="text-[10px] font-black text-slate-400 dark:text-slate-500 uppercase tracking-widest mb-1">Contraindications</p>
                          <p className="text-sm text-slate-700 dark:text-slate-300 leading-relaxed">{rec.contraindicationSummary}</p>
                        </div>
                      </div>

                      <div className="flex items-start gap-3">
                        <div className="w-8 h-8 rounded-lg bg-indigo-50 dark:bg-indigo-900/30 flex items-center justify-center text-indigo-600 dark:text-indigo-400 flex-shrink-0">
                          <ArrowRightLeft size={16} />
                        </div>
                        <div>
                          <p className="text-[10px] font-black text-slate-400 dark:text-slate-500 uppercase tracking-widest mb-1">Therapeutic Logic</p>
                          <p className="text-sm text-slate-700 dark:text-slate-300 leading-relaxed">{rec.comparisonReason}</p>
                        </div>
                      </div>
                    </div>
                  </div>
               </div>

               <div className="mt-8 pt-6 border-t border-slate-100 dark:border-slate-800 flex items-center justify-between">
                  <div className="flex gap-2">
                    <span className="px-3 py-1 bg-emerald-100 dark:bg-emerald-900/40 text-emerald-700 dark:text-emerald-300 text-[10px] font-black rounded-full border border-emerald-200 dark:border-emerald-800">CLINICALLY SUPERIOR</span>
                    <span className="px-3 py-1 bg-blue-100 dark:bg-blue-900/40 text-blue-700 dark:text-blue-300 text-[10px] font-black rounded-full border border-blue-200 dark:border-blue-800">LOW INTERACTION RISK</span>
                  </div>
                  <button className="flex items-center gap-2 text-blue-600 dark:text-blue-400 text-xs font-bold hover:underline">
                    View Comprehensive Efficacy Study <ArrowRightLeft size={14} />
                  </button>
               </div>
            </div>
         )) : (
            <div className="p-20 bg-slate-50 dark:bg-slate-900/50 rounded-[40px] text-center border-2 border-dashed border-slate-200 dark:border-slate-800">
              <HeartPulse size={48} className="text-slate-300 dark:text-slate-700 mx-auto mb-4" />
              <p className="text-slate-500 dark:text-slate-400 font-medium italic">No detailed therapeutic alternatives found for this medication profile.</p>
            </div>
         )}
      </div>

      <div className="glass-panel p-10 rounded-[40px] border border-white dark:border-slate-800 shadow-xl mt-8">
        <div className="flex flex-col md:flex-row items-start md:items-center gap-6 mb-10">
           <div className="w-14 h-14 bg-amber-50 dark:bg-amber-900/20 text-amber-600 dark:text-amber-400 rounded-2xl flex items-center justify-center flex-shrink-0 shadow-sm border border-amber-100 dark:border-amber-800"><AlertCircle /></div>
           <div>
             <h3 className="text-2xl font-bold text-slate-900 dark:text-white">Professional Safety Disclaimer</h3>
             <p className="text-slate-500 dark:text-slate-400">Essential protocol for clinical implementation of AI recommendations.</p>
           </div>
        </div>
        <div className="grid md:grid-cols-2 gap-8">
           <div className="p-8 bg-amber-50/50 dark:bg-amber-900/10 rounded-3xl border border-amber-100 dark:border-amber-800/50 text-amber-800 dark:text-amber-200 leading-relaxed font-medium">
             Therapeutic recommendations provided by this AI are based on complex clinical datasets and pharmacological modelling. These suggestions should be evaluated by the primary attending physician before any prescription changes are made.
           </div>
           <div className="space-y-4">
              <p className="text-[10px] font-black text-slate-400 dark:text-slate-500 uppercase tracking-widest ml-2">Clinical Verification Checklist</p>
              <div className="grid gap-3">
                 {[
                  "Verify patient specific allergy profile", 
                  "Assess current renal and hepatic clearance rates", 
                  "Final physician signature & authorization",
                  "Review patient's secondary polypharmacy chart"
                 ].map(step => (
                    <div key={step} className="flex items-center gap-4 p-4 bg-white dark:bg-slate-800 rounded-2xl border border-slate-100 dark:border-slate-800 transition-colors shadow-sm">
                       <div className="w-6 h-6 rounded-full bg-emerald-50 dark:bg-emerald-900/20 border border-emerald-100 dark:border-emerald-800 flex items-center justify-center text-emerald-600 dark:text-emerald-400">
                        <CheckCircle2 size={14} />
                       </div>
                       <span className="text-sm font-bold text-slate-700 dark:text-slate-300">{step}</span>
                    </div>
                 ))}
              </div>
           </div>
        </div>
      </div>
    </div>
  );
};
